### ISSUE TITLE
Enhancements on used dependencies detection

### ISSUE THREAD

**Issue by HenKun** [yireo/Yireo_ExtensionChecker#12]
As you stated, you want to refactor this extension. I put some thoughts on this, which will also address issues #6 and #7 

First, you proposed using a kind of composite to get dependencies and to be extendable. I think this is the right way to go.

Disclaimer: There might be too much details already, but I was in a flow, so first here is a tl;dr. 
I would also contribute code if you want to start a refactoring.

# tl;dr

- `DependencyDetectorInterface` is the top level entrypoint, implemented as composite
- Different implementations exist: `ClassDependencyDetector`, `JsDependencyDetector`, ...
- `ClassDependencyDetector` uses `ClassDetectorInterface` (implemented as composite) and transforms detected classes to module and composer dependencies
- `ClassDetectorInterface` is implemented by different detectors like `PhpFileParsingClassDetector`, `DiFileParsingClassDetector` and more
- `PhpFileParsingClassDetector` reflects all classes and passes each to different `PhpClassDetectorInterface`s which in turn extract different class dependencies from a given class. [BetterReflection](https://github.com/Roave/BetterReflection) can be used to easily gain required insights.

# Details

Let's start with a `ClassDetectorInterface` which is basically implemented by a Composite that contains n `ClassDetectorInterface` implementations.

One concrete implementation of `ClassDetectorInterface` will be `PhpFileParsingClassDetector`. This class could use [BetterReflection](https://github.com/Roave/BetterReflection) to parse all PHP files in the given module/directory. `PhpFileParsingClassDetector` in turn is implemented as a kind of composite. First it parses all files extracting `ReflectionClasses` and afterwards passes each `ReflectionClass` to each of the contained `PhpClassDetectorInterface` implemetation.  

The following implemetations can be thought of for `PhpClassDetectorInterface` (All implementations can use BetterReflection, it's simple to get everything needed):

`ParentDetector` => Returns the parent class if existent
`InterfaceDetector` => Returns the immediate Interfaces the class implements 
`TraitDetector` => Returns all traits the class uses
`PropertyDetector` => Returns the immediate declared property types
`MethodDetector` => Returns all input types and return types of all methods in this class, both from PHP 7 type hints and from Doc comments.
`ConstFetchedDetector` => Returns all classes the current class uses to access consts from
`StaticVariableFetchedDetector` => Returns all classes the current class uses to access static variables from
`StaticCallDetector` => Returns all classes the current class executed static methods on
`ClosureDetector` => Returns all classes used in Closures
...

Besides the `PhpFileParsingClassDetector` implementation of `ClassDetectorInterface`, there will be a `DiFileParsingClassDetector`, which in turn is again a kind of composite that serves different `DiClassDetectorInterfaces` with each di file. Possible implementations could be:

`TypeDetector` => Returns all classes extracted from `<type name="XY" .. >` statements (Yes, type can be an external class, e.g. when wanting to pass different arguments)
`VirtualTypeDetector`  => Returns all classes extracted from `<virtualType type="XY" .. >` statements
`PreferenceDetector`  => Returns all classes extracted from `<preference for="XY" .. >` statements
`PluginDetector` => Returns all classes extracted from `<plugin ..>` statements (This can be hard. One could reference a plugin of an external module by name., e.g. to disable it. Won't be easy to detect the class type the plugin uses)
`ArgumentsDetector` => Returns all classes extracted from `<argument name="foo" xsi:type="object">XY</argument>` statements

We go on with a third implementation of `ClassDetectorInterface` that is the `LayoutFileParsingClassDetector`. Again, this can be implemented of kind of composite that serves n `LayoutClassDetectorInterface`s. Possible implementations:

`BlockDetector` => Returns all classes extracted from `<block class="XY"` (Yes, this can be external classes)
`ContainerDetector` => Returns all classes extracted from `<container class="XY"` (Yes, this can be external classes)
`ReferenceBlockDetector` => Hard to implement because identified by name only
`ReferenceContainerDetector` => Hard to implement because identified by name only
`MoveDetector` => Hard to implement because identified by name only
`UiComponents` => No clue

A fourth:  `UiComponentFileParsingClassDetector` that passes each file to n `UiComponentClassDetectorInterface`s.

`ColumnDetector` => Returns all classes extracted from `<column name="foo" class="XY">` statements
`OptionsDetector` => Returns all classes extracted from `<options class="XY"/>` statements
... I can imagine there are plenty more classes to detect in ui component files ...

There could be more implementations of `ClassDetectorInterface` besides those four waiting to be implemented.

Based on those extracted classes, as it is already done now, composer.json dependencies and module.xml dependencies could be generated. 

But dependencies need not only be those classes (traits/interfaces). As in #6 stated, we can extract dependencies from JS Files. But also from layout xml files, like in the `head` section: `<css src="Vendor_Module::css/foo.css" />`. Or from UI component files like `<column name="foo" component="Magento_Ui/js/grid/columns/select"`. Or even from menu.xml like `<add id="XY::base"              title="Foo" module="XY" parent="Dependend_Module::menu" resource="Dependend_Module::edit"/>`

So we need a more general interface `DependencyDetectorInterface`. 

First implementation could be a `ClassDependencyDetector` that uses the composite implementaion of `ClassDetectorInterface` to transform Classes to composer and module dependencies. 

As you can imagine `DependencyDetectorInterface` is implemented as a composite. 

Besides `ClassDependencyDetector` there could now be a `JsDependencyDetector` that can parse js or require js files smartly, extracting referenced JS components and the modules that provide those. And a `AclResourceDependencyDetector` to parse different files for used acl resources. An `AssetDependencyDetector` that checks files for added or removed assets. An`UiComponentDependencyDetector` that parses files and extracts used components and mapps that to the corresponding module.

I think there are plenty more places where dependencies could be detected.
Due to this "level" structure and the use of composites, one can easily add new detectors on different abstractions by just implementing an interface and adding it to the right composite.

Things to consider:

- What dependencies should actually be detected. Only hard ones or also soft ones? E.g. is adding a custom menu item to an existing parent menu item from another module a dependency to that module? I would say yes, but this is arguable.

- Do all dependencies in module.xml be reflected in composer.json and vice versa? There was a ticket somewhere on trying to get rid of module.xml and only use composer.json, but there were valid complaints, that modules declared in module.xml need not be required by composer, but are just optional, so IF the module is present, the sort order is right.

**Comment by jissereitsma** [comment]
Wow, this is awesome. You have already put so much work in this. Unfortunately, I lack the time currently to dive really deep into this: Currently working my ass off in weekends to meet deadlines.

Reading through your proposal, I like it that not only the "reporters" are modularized but also the "detectors". I hope to take a closer look later.

**Comment by jissereitsma** [comment]
A long time you invested in this to come up with a new architecture. Finally, I had some time to restructure things. Not exactly in the way as you suggested, but the logic of the old `Scan` class (which grew larger and larger) is now chopped into smaller pieces - I call them `ComponentDetectors` because Magento refers to libraries, modules and language packs as components. The rewrite is still underway with various cool features like a better CLI, JSON output and an aweful lot of integration tests. I'm closing this issue as of yet, but would like to thank you again for investing time into this and coming up with great ideas here!
