### ISSUE TITLE
merge conflict committed

### ISSUE THREAD

**Issue by riconeitzel** [yireo/Yireo_ExtensionChecker#15]
Hey Jisse, 

that's a big issue at the moment 😄

https://github.com/yireo/Yireo_ExtensionChecker/blob/5bd9235c57994c083a8c69062cee646c29dd0f69/Console/Command/RunUnitTestCommand.php#L62-L66

Rico

**Comment by jissereitsma** [comment]
Thanks for pinging me. I fixed this already but the commit was still pending while on vacation :( Fix is pushed now
