### ISSUE TITLE
Issue With Non-Existent Module

### ISSUE THREAD

**Issue by sprankhub** [yireo/Yireo_ExtensionChecker#17]
If a module is inside `app/etc/config.php`, but not installed, I get the following error:

    Return value of Yireo\ExtensionChecker\Scan\Module::getModuleFolder() must be of the type string, null returned#0 /var/www/html/vendor/yireo/magento2-extensionchecker/Scan/Scan.php(152): Yireo\ExtensionChecker\Scan\Module->getModuleFolder('Vendor_Module')

Would probably be better to ignore such modules?

Thanks as always :)

**Comment by jissereitsma** [comment]
Who is such a bastard to leave non-existing modules in `app/etc/config.php`? Haha.

Fixed in https://github.com/yireo/Yireo_ExtensionChecker/commit/a4c6fa500f2e560446d9a0f05a8a4c14318e7c5a

**Comment by sprankhub** [comment]
:grin: Thanks!
