### ISSUE TITLE
JSON Syntax error When Run Via Bitbucket Pipelines

### ISSUE THREAD

**Issue by sprankhub** [yireo/Yireo_ExtensionChecker#18]
We run the extension checker inside Bitbucket Pipelines. A few days ago, it suddenly started failing with the following issue:

    + bin/magento module:status --enabled | grep Vendor_ | while read -r MODULE; do echo "Checking $MODULE"; bin/magento yireo_extensionchecker:scan --module "$MODULE" --hide-needless 1 --hide-deprecated 1 || exit; done
    Checking Vendor_Module
    In Json.php line 39:
                                                        
      Unable to unserialize value. Error: Syntax error 

I found out that this is caused by the analysis of the Composer packages:

https://github.com/yireo/Yireo_ExtensionChecker/blob/e06da4767a91ca315a5d71df59df0dbb4381ad9a/Scan/Composer.php#L121-L122

By default, actions in Bitbucket Pipelines are run with the `root` user and somehow, `composer show --no-scripts --no-plugins --format=json` suddenly shows a warning in the first line of the output, which seems to break the JSON:

    + composer show --no-scripts --no-plugins --format=json
    Do not run Composer as root/super user! See https://getcomposer.org/root for details
    {
        "installed": [
            {

I could not find out why this came up just now. One possible fix is to run `export COMPOSER_ALLOW_SUPERUSER=1` in your pipeline, which pretty much disables the warning.

For reference, the warning is triggered here:

https://github.com/composer/composer/blob/a3f7c31ea76fa8e22811df2e0ac156925f64da58/src/Composer/Console/Application.php#L280-L304

It could theoretically be caused by the [latest `containerd` upgrade in Bitbucket Pipelines](https://confluence.atlassian.com/bbkb/infrastructure-changes-in-bitbucket-pipelines-1142431176.html), but I really cannot tell.

I do not see a nice solution to fix this inside the extension. Using Composer's `--quiet` also removes the valid JSON output, so this is not an option. We could add the `COMPOSER_ALLOW_SUPERUSER` environment variable to the `composer show` command, but not sure if we should do this.

@jissereitsma, if you have any thoughts here, feel free to comment. Otherwise, this is just a nice documentation for the issue (I hope) and can be closed.

**Comment by jissereitsma** [comment]
Hmm, this is not the only issue I've encountered with this. If you pass the verbose flag to `bin/magento` this is also being transferred to the `composer` command, adding yet again more stuff to the JSON output.

I'd rather live with all of these messages and simply throw a regex to remove all lines before the first `{` opening brace. Does that sound like an option to you?

**Comment by sprankhub** [comment]
Sounds ugly as hell, but if it helps, why not :joy: :man_shrugging:

**Comment by jissereitsma** [comment]
Like so: https://github.com/yireo/Yireo_ExtensionChecker/commit/40df196c6ddc3358e9fde7c3aa11b9fcaacaa0c0

Does this work for you?

**Comment by sprankhub** [comment]
It should :) Thanks Jisse!
