### ISSUE TITLE
Show Error When No composer.json Present

### ISSUE THREAD

**Issue by sprankhub** [yireo/Yireo_ExtensionChecker#2]
If there is no `composer.json` at all, the following error is shown:

    Unable to unserialize value.

You probably want to handle that issue in a better way :-)

**Comment by jissereitsma** [comment]
Fixed in https://github.com/yireo/Yireo_ExtensionChecker/commit/0ff6ff0b8fa4b76c01da2b15d9ef96dfdb56e118#diff-b53a49a5b22d6a40e5e7585f0b34b7aa
