### ISSUE TITLE
Does not find packageName for "Hyva_GraphqlViewModel"

### ISSUE THREAD

**Issue by norgeindian** [yireo/Yireo_ExtensionChecker#22]
In one of our local modules, we have a dependency on `Hyva_GraphqlViewModel`, which we define like we should.
Unfortunately, the check for this module seems to fail, as the `packageName` is not found.
When debugging into `scanComposerDependencies`, I see the following component:
```
Yireo\ExtensionChecker\Component\Component Object
(
    [componentName:Yireo\ExtensionChecker\Component\Component:private] => Hyva_GraphqlViewModel
    [componentType:Yireo\ExtensionChecker\Component\Component:private] => module
    [packageName:Yireo\ExtensionChecker\Component\Component:private] => 
    [packageVersion:Yireo\ExtensionChecker\Component\Component:private] => 
)
```
Any idea, why this goes wrong? The module can be found at https://github.com/hyva-themes/magento2-graphql-view-model

**Comment by jissereitsma** [comment]
I'm unable to duplicate this issue, but I'm not sure which steps you took either:
```bash
composer require hyva-themes/magento2-graphql-view-model
bin/magento mod:en Hyva_GraphqlViewModel
bin/magento yireo_extensionchecker:scan --module=Hyva_GraphqlViewModel
```

Are you sure you're scanning this with all relevant modules enabled?

**Comment by norgeindian** [comment]
@jissereitsma , thanks for checking directly.
But it's a bit the other way round. We have a custom module and this one has a dependency on `Hyva_GraphqlViewModel`, which we properly define in the module.
Then we're scanning this custom module using the extensionchecker and get the following error:
`Dependency "" not found composer.json.`
When I then debugged, I saw, that the package is `Hyva_GraphqlViewModel` and the check in `scanComposerDependencies` fails, because the `$packageName` is just empty, although the dependency is defined.
Do you see any obvious issues in the module, which would explain, why the scanner does not find the name or is it easy for you to shortly check, if you can reproduce the issue using the approach described?
If not, I can create a dummy module, where you can reproduce it.

**Comment by jissereitsma** [comment]
Hmm, strange. First of all, just to make sure: The module `Hyva_GraphqlViewModel` has been enabled correctly in the environment you're using the ExtensionChecker with?

**Comment by jissereitsma** [comment]
I dived into this myself already a bit. In Magento, there is a hard requirement to have the `composer.json` in the root of the module itself. In the case of the `Hyva_GraphqlViewModel` module, the module is located in the `src/` folder of the composer package instead. This causes the system call `vendor/magento/framework/Module/Dir/Reader.php` line 96 to fail, which is again used by the Yireo ExtensionChecker.

**Comment by jissereitsma** [comment]
I've provided a workaround for this in release 1.2.17. Could you see if this works for you?

**Comment by norgeindian** [comment]
@jissereitsma , thanks a lot for this fix. Yes, works perfectly now. Thanks.
