### ISSUE TITLE
Expecting Variable Error during setup:di:compile

### ISSUE THREAD

**Issue by norgeindian** [yireo/Yireo_ExtensionChecker#23]
I just included version `2.0.0`.
When I now run `setup:di:compile`, I get the following error:
`Parse error: syntax error, unexpected ')', expecting variable (T_VARIABLE) in /var/www/html/vendor/yireo/magento2-extensionchecker/Message/Message.php on line 23`.

Does anyone run into the same problem?

**Comment by jissereitsma** [comment]
Whoops, this is due to a comma in the constructor which is supported by PHP 8.1, but not 7.4. Believe it or not, I was busy all day with PHP compatibility issues with this extension and others, but with the final 2.0.0 release I overlooked the PHP 7.4 check. This is now fixed in 2.0.1.

**Comment by norgeindian** [comment]
Like always, thanks a lot for your fast reply and solution.
Indeed, version 2.0.1 also runs smoothly on PHP 7.4 now. 
Thanks.
