### ISSUE TITLE
--hide-needless Flag Ignored

### ISSUE THREAD

**Issue by sprankhub** [yireo/Yireo_ExtensionChecker#29]
Looks like this flag is ignored in version 2.1.2? Even if I run the command with this flag, unnecessary composer dependencies are reported. Also, if I search for it in the code, it is not checked anywhere:

![image](https://user-images.githubusercontent.com/930199/194575480-b1fd6bb8-fc92-414b-8d01-d1d91f5b4e36.png)

Or maybe I misunderstand the flag?

**Comment by jissereitsma** [comment]
When refactoring the old code inside out, this dropped off the radar. I've reimplemented the flag here: https://github.com/yireo/Yireo_ExtensionChecker/commit/196b823db1b89a9055d4b9efb1148664001e3d1a

**Comment by jissereitsma** [comment]
This should now be fixed in 2.1.3.

**Comment by sprankhub** [comment]
Thanks!
