### ISSUE TITLE
[release] composer.json in master differ thant v1.0.0

### ISSUE THREAD

**Issue by julienanquetil** [yireo/Yireo_ExtensionChecker#3]
In v1.0.0 the composer.json requiere "symfony/finder": "^4.0"
In my case (2.2.7) I got symfony/finder v3.4.21

But in your master branch you update the composer.json to allow  "symfony/finder": "^3.0|^4.0",
which can "solve" my error 

thanks

**Comment by jissereitsma** [comment]
Whoops, sorry for that. Version 1.0.1 is now released.
