### ISSUE TITLE
magento/zendframework1 Dependency Not Detected

### ISSUE THREAD

**Issue by sprankhub** [yireo/Yireo_ExtensionChecker#30]
I checked a module, which injects `Zend_Filter_Interface` in the constructor of a block. The class is part of `magento/zendframework1`. However, this dependency is currently not catched (it might have worked in older versions). Even worse, it says "Composer requirement "magento/zendframework1" possibly not needed" if I require it manually.

**Comment by jissereitsma** [comment]
This is fixed in https://github.com/yireo/Yireo_ExtensionChecker/commit/53a1f80578f177ff8feb7652cddb667e10fdf69e

**Comment by jissereitsma** [comment]
This should now be fixed in 2.1.3.

**Comment by sprankhub** [comment]
Thanks!
