### ISSUE TITLE
Add an option to "exit 1" if some unmentioned decencies found

### ISSUE THREAD

**Issue by hws47a** [yireo/Yireo_ExtensionChecker#5]
To allow pipeline to fail it could be a good idea to return "1" when some output found.
It can be added as an option, so pipelines won't fail for existing users of the module.

**Comment by jissereitsma** [comment]
Done. https://github.com/yireo/Yireo_ExtensionChecker/commit/5112aa58b6d1bcf08a6b2f50558237f76883e26d

**Comment by hws47a** [comment]
Thank you @jissereitsma
