### ISSUE TITLE
A "No dependencies for" when the module has no sequenece

### ISSUE THREAD

**Issue by iranimij** [yireo/Yireo_ExtensionChecker#51]
When I try to run the extesion checker test. this lines returns error 

https://github.com/yireo/Yireo_ExtensionChecker/blob/069f4669418fc93796543fe1440cf923d7a00097/ComponentDetector/ModuleXmlComponentDetector.php#L42C1-L44C10

and since we can not add a dependency on the framework, I think we should remove this validation

**Comment by jissereitsma** [comment]
I'm closing this, in a futile attempt to get rid of backlogs. And I hope I can keep on closing tickets or merging PRs :)
