### ISSUE TITLE
Update nikic/php-parser ^5.0

### ISSUE THREAD

**Issue by alicedfisheye** [yireo/Yireo_ExtensionChecker#55]
Please can you change https://github.com/yireo/Yireo_ExtensionChecker/blob/master/composer.json#L22C5-L22C37 to `"nikic/php-parser": "^3.0|^4.0|^5.0",` so that I can update the module.

**Comment by jissereitsma** [comment]
Sure thing: https://github.com/yireo/Yireo_ExtensionChecker/commit/7a7ef9a667f0d3310da5dec4492cbb1f3d1d2e9a

**Comment by alicedfisheye** [comment]
@jissereitsma You're an angel <3
