### ISSUE TITLE
File does not have a "require-dev" Error

### ISSUE THREAD

**Issue by iranimij** [yireo/Yireo_ExtensionChecker#56]
The latest version has a problem, and the problem is that when a module does not have require-dev it returns below error : 
`File XXX does not have a "require-dev" `

The error comes from this line where we added `require-dev`

https://github.com/yireo/Yireo_ExtensionChecker/blob/9438b2fdac577630c18f7c58ceec5d9fc9827884/Composer/ComposerFile.php#L87

**Comment by jissereitsma** [comment]
Thanks for the report. I've refactored things to bypass the exception instead: https://github.com/yireo/Yireo_ExtensionChecker/pull/57
